### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Felli** [GreenVolume/humhub-modules-privacybox#1]
At the moment Translations are needed, and always wanted! :smiley: 

- [x] English Template (en_US) by @GreenMeteor #2
- [ ] Chinese (zh_cn) #4
- [x] Japanese (ja) by @GreenMeteor #7
- [x] Spanish (es) by @oyepez003 #6
- [ ] Korean (ko) #5
- [ ] Other

**Comment by oyepez003** [comment]
I just added the Spanish (es) language.

https://github.com/GreenVolume/humhub-modules-privacybox/pull/3
